language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: G+eOXvl6SLciUgcfrkMvuQmSYkN8vdb8HLglqhz69kVd9LILkWbBuHqCImv27i+ZQ5oj0dD1qr60MTm13rjmSlForA9kKLfRN7RccdS2EoHRoA+PjmCCcUdgbVVL/ZOB9BLNL+1NX9Opczq9W9SAcsCuKacBy7BlB5V1jmC9mSdCmPmSkVWm4WvaK6TSod8VNkKXhcka279lJ85O1TCpraTPsiV3vTaFwPhNIU9PX2V800sZizC/7cLLug6hPcARX9pbPGSlYtMW71/eknHrHv1Kc9Oyw4CQx9fMIWMw6dgeTFNwWBttMyDmlFdkdMs0qM29556vl31cudosM0ZoV4ejDgyyKrwS+QdzdYIh89hXLKfm4LnPcdg5VN1nNZ0c/Hi94O2YjY9/6q9NKzz83b4JAVmkUcZfXY28Z7voVrBnRrHV08cyljTsg92PQVsVDaYC/SQ6GexANxxx7ykGNPPRe1luJ+gNhj1FxW27vQJ51zi9PPh/KeYFmJ9jTcn5FkrgwrW16jfsZQ/GRwjjOmNPPq+6BFpLGpQtaXlMy/7U0jlrfDLoAhoCy1M7Xz5PVKkqzT+aEJG5t9Im3iJfwCUl9QINsEHfb3ZdYCOyep7MihfrsKfZilSB/5ocGDklCtRGT5fqsXwtV2JjU6xjQIgdyJGWT5iEH5Yy/iXOTZk=
  app: enigmatic-spire-11813
  on:
    repo: raysmithdev/chappy-nest-api
