 language: node_js
 node_js: node
 services:
     - mongodb

deploy:
  provider: heroku
  api_key:
    secure: kUeXcTNqLJW1ZPnmO70aMHKpSiIkb21Uvqsj1iDOVfseYyvBTQ237DRg8eqLoPzEUyyiH+2LAZ0tigQHIpF8v9c4R/xDnZB7w5I0j5vybCC/IdaT4yEhiFt7KvUPQnj8pK0OrGshii2ht8K6YCgoFMOUCduNSCSFimLXiHFqGnlCHNonqRO1zjJI2Ni3c7EdcQoU+FG/V0rQpNJAC179KmJBv21VSywTwcrqSjxHu68+6himaxZM1mLHsr8SsiJvJwkLTFvcl5uKRSvTQzE82g0EqpD4SLhtoZdpjw3UtQn9hvePC7+X16Yc/N9vE/ufH4jmHRkqJ9n/MSa3HtMG1R2KoskAsLjyaZFkdcsNL8tbyQnX9GUv9lDvJwwQ8z5SAmeHpOvMBaakkdg1xYxQZfvb2xIdvzHD5DdCqmWZrmGnhTJTGfjIAUx1MDFMQkiqFykgwbyTcHLh9vizJjrLonSTuAI8E2N1Vbs8nPdqU7JWov8DK64xRJwsZvvrg07G+FDBwl5i8s78Z/28UZhpcIT+vgYx5KzTkwOjHxy3oOqUnT3PyKJixapVbaMJHmRw6O+SSgfuveCbNKdvQwbCBGosLB8xoh9Ae1YrhxlZgP9ujcDJrAZvif3+/jfERf6DQuwV8B6UtODr1NX5/dmtopRzQWt15X+nZBoCl2LYtCA=
  app: https://git.heroku.com/mighty-escarpment-24353.git
  on:
    repo: jbuchanan89/chappy-nest-api
