language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: hLobUbxJaEBp0lzCHlRSFNBdS0AMEUKQhNAAce4akfUSN5BPutBL/qsBr3+0pLJScxt8foAoKp3o3eGr7O3TtGobR+vdaUD+sJbvMvY6xizZcxqiC3VOdsJJrh2vaDL0BJBi4FvvceQV+C5ilRasCVdQyoht8VW8oK9KFWB85quTSUa2nqR3gOi1pZF35jwYQLHD6Nr3Qfew1ks9sT0WRkmY5+eN5Tgc2w5Dh2EOyiaXm47cXyYZcXA/3hd4Ja9Oagq/SJEvgyp9En6fIHG6QDW5F7Er3eyXw8qP7GS2TUBXGqjrpR8G6TM4nd8oRgFKXyH8LnNiJNC9moxWM1cD3LlBy+X0mrCyIZRX0azbm7uUvnbEiv2G1kwie31lhy/zaxe/IvCuGtX408DXP5ikuVylpJVKgvU4D5wksHKcM5HVAQhnWuPGLE0q6Dn2pqQsGfoaMeQfqIvf6L5qIng31t94I3nqwvvHHHUZ24VCjAVyHqOGIxJtu9T/YidILkxTY9+0zs/ELzMOC+cN8PePkC65mNP/TaLmePV4SS4Hm0N0tuwOLMVXgZO/ihzAiZ+0mEsRi1ikysIEXV5CoM6xCIy67q31hbd6Eu5uErA2hqMesQnJCIcbIufMgkmoQ2/Db9ziXPUybz/FpR4xnf7x7uLV50mu1trwJilHPXak1TA=
  app: morning-thicket-60175
  on:
    repo: jbuchanan89/chappy-nest-api
